### PR TITLE
Fix case when sAMAccountName is not set

### PR DESCRIPTION
**Pull request by rtpt-romankarwacik**

### CODE REVIEW

**Comment by CravateRouge** [comment]
Thank you for your contribution!

Could you show me the object you had with an objectSID without sAMAccountName?

**Comment by rtpt-romankarwacik** [comment]
It occured only when resolving the security descriptor of a cross-domain certificate template, so some objects in it could apparently not be properly resolved. Unfortunately I cannot share it though.

**Comment by CravateRouge** [comment]
In this case it seems this PR would only hide the real issue. It would be more interesting to have code to fix this cross domain resolution issue, what do you think?

**Comment by rtpt-romankarwacik** [comment]
You're right, but to do this the `ForeignSecurityPrincipals` object would need to be properly resolved, by retriving the object from the corresponding forest before returning the `sAMAccountName`. Unfortunately I currently don't have the time, so this pull request would serve as a first workaround until that is properly implemented.

**Comment by CravateRouge** [comment]
Yes I have to work on some cross domain function helpers to solve easily this kind of situations.

Waiting for that I will add this change so user can still have information displayed.

**Pull request merged**
